### ISSUE TITLE
How to prevent the pickler from using fully qualified names?

### ISSUE THREAD

**Issue by thomasd3** [nessos/FsPickler#124]
I have an error where un-pickling data triggers this error:

it expects:

'Microsoft.FSharp.Collections.FSharpMap`2[IExchange.Instrument,Testing+TrendAnalysis[]]'

but got:
'Microsoft.FSharp.Collections.FSharpMap`2[IExchange.Instrument,Program+TrendAnalysis[]]'

The object to deserialize to is the same, I just relocated it in the project. How can I prevent it from using the full name of the object so that the definitions can be moved around?

**Comment by eiriktsarpalis** [comment]
Per documentation in http://mbraceproject.github.io/FsPickler/ the serializer is not designed with version tolerance in mind. That being said, it should be possible to work around that issue by providing a custom implementation of the [ITypeNameConverter](http://mbraceproject.github.io/FsPickler/reference/mbrace-fspickler-itypenameconverter.html) interface.
