### ISSUE TITLE
Extenally marking types as excluded/nonserialized/serializable

### ISSUE THREAD

**Issue by damageboy** [nessos/FsPickler#26]
Hi,
I'm trying to dump my current serialization setup for a a large object graph of types I have.

The way I've started to work with FsPickler is to start sprinkling Serializable attributes all over my code.
This it perfectly acceptable, but the problem I'm experiencing is with non Serializeable types.

I would like to be able to somehow inform FsPickler that a *type* is not serializable (rather than marking each field in other classes that is of that type).

I cannot seem to find this ability in the current code in FieldPicklers.fs or anywhere else in FsPickler.

I would like to work on this, but I thought that it would be better to start some sort of a discussion on how these things should be done.

I can see two approaches:
1. Add something along the lines of a NotSerializableAttribute class that would come from FsPickler...
This sounds like a very BAD idea, since it would mean that user code now actually depends on FsPickler, and would generally suck, so I don't think this is even worth pursuing 
2. Provide a Set/List of excluded types, so that when FsPickler encounters these types, it will automatically treat the fields that points to these types *as-if* they were marked with the NonSerialized attribute

In addition to what I've outline in (2), the same idea could be applied for the use of SerializableAttribute, i.e., another Set/List  could be supplied that would contain types that SHOULD be treated as Serializable even if they are not marked as such through the Serializable attribute. This will have the additional advantages:
* No changes are needed for existing code, only the code performing the serialization needs to care about who/what gets serialized
* Support for "adding" serialization for binary/compiled code that doesn't have the Serializable attribute but could be serialized otherwise can be done post-fact

Any thoughts?
Is the direction of adding Sets of Types to the (de)serialization api-points acceptable?

**Comment by eiriktsarpalis** [comment]
This has been partially addressed as of 1.2.5, closing.
