### ISSUE TITLE
CustomPickler forces other projects to reference FsPickler

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [nessos/FsPickler#32]
I have an F# record and one of its fields is the result of an expensive calculation derived from the other fields. Currently this is not lazy, although it might be in the future, but even so the idea is to avoid performing the calculation more than once.

The field is quite a large data structure, so I don't want to save it. Instead I want to recalculate it when I restore the object. Since this is an immutable F# record, `ISerializable` and `DataContract` are unsuitable, so the `CustomPickler` attribute seems like the only way to go.

The problem is that even if the static `CreatePickler` method is made private, calling projects need to include FsPickler due to the `IPicklerResolver` method argument. The compiler error is:

    error FS0074:
    The type referenced through 'Nessos.FsPickler.IPicklerResolver' is defined in an assembly that is not referenced.
    You must add a reference to assembly 'FsPickler'.

My calling projects are not concerned with data serialization, so it doesn't seem right that they should have to include FsPickler. Can you think of a way around this problem?

David.

**Comment by eiriktsarpalis** [comment]
This has been partially addressed as of 1.2.5, closing.
