### ISSUE TITLE
NonSerializableTypeException with ISerializable types

### ISSUE THREAD

**Issue by danielrbradley** [nessos/FsPickler#42]
I'm trying to serialize types (e.g. ZonedDateTime) from the NodaTime library which are [marked as ISerializable](http://nodatime.org/1.3.x/userguide/serialization.html) ([source](https://github.com/nodatime/nodatime/blob/master/src/NodaTime/ZonedDateTime.cs#L766)), though also contain non-serializable fields. When generating a pickler using:

    let p : Nessos.FsPickler.Pickler<NodaTime.OffsetDateTime> = Nessos.FsPickler.FsPickler.GeneratePickler()

it throws NonSerializableTypeException: Type 'NodaTime.OffsetDateTime' contains non-serializable field of type 'NodaTime.CalendarSystem'.

Should FsPickler prefer the ISerializable implementation over field based serialization? Alternatively, should we encourage NodaTime to support DataContract based serialization instead?

**Comment by eiriktsarpalis** [comment]
That's clearly a bug. Fixed in 3bea2d5f2887f7cce51a56a809c7b2cdf82d0411.

**Comment by danielrbradley** [comment]
Amazing, thanks for the quick response! :+1:

**Comment by eiriktsarpalis** [comment]
Just updated to nuget package version 1.0.17.
