### ISSUE TITLE
FsPickler.Json: Version of Newtonsoft.Json 

### ISSUE THREAD

**Issue by ascjones** [nessos/FsPickler#48]
Hi Eirik

I want to upgrade to 1.2.5 (for the excellent new custom pickler registration feature), but am unable to because the version of Newtonsoft.Json in FsPickler.Json is now pinned to 6.0.5 since the Paket upgrade:

![image](https://cloud.githubusercontent.com/assets/75586/7956324/1482bd66-09d7-11e5-8443-044c3c226a3e.png)

In version 1.2.4 it was (perhaps not intentionally) unrestricted above 6.0.5:

![image](https://cloud.githubusercontent.com/assets/75586/7956360/4477acde-09d7-11e5-8699-de1aef6a0973.png)

Another of my dependencies depends on the latest stable: 6.0.8, and since I'm using Paket it resolves to the latest version with compatible version constraints: in this case 1.2.4

Just checking that this is intentional, since I know that Newtonsoft.Json is not exactly famous for confirming to SemVer between patch versions. However it could just be a consequence of the Paket conversion.

If so I suggest relaxing the version constraint in paket.dependencies to ```~> 6.0.5```, which I believe will resolve to >= 6.0.5 && < 6.1 in the nuspec. This is slightly tighter than the original >= 6.0.5 constraint.

Cheers,

Andrew

**Comment by eiriktsarpalis** [comment]
Yes, this was caused inadvertently in the recent migration to `paket pack`. It's been fixed in `1.2.6`.

**Comment by ascjones** [comment]
Thanks for the quick fix Eirik!
