### ISSUE TITLE
dependency on the older version of the Newtonsoft.Json

### ISSUE THREAD

**Issue by leo-gan** [nessos/FsPickler#50]
Hi,
Is it possible to upgrade to a new version of a Newtonsoft.Json or just modify nuget package that it can accompdete a new Json.net?
I'm getting an error:
Attempting to resolve dependency 'Newtonsoft.Json (≥ 6.0.5 && < 6.1.0)'.
Installing 'FSharp.Core 3.1.2.1'.
Successfully installed 'FSharp.Core 3.1.2.1'.
Installing 'Newtonsoft.Json 6.0.5'.
Successfully installed 'Newtonsoft.Json 6.0.5'.
Installing 'FsPickler.Json 1.2.9'.
Successfully installed 'FsPickler.Json 1.2.9'.
Installing 'FsPickler.CSharp 1.2.9'.
Successfully installed 'FsPickler.CSharp 1.2.9'.
Install failed. Rolling back...
Install-Package : Already referencing a newer version of 'Newtonsoft.Json'.

- but I have to use the "Newtonsoft.Json" version="7.0.1"

Thanks!

**Comment by eiriktsarpalis** [comment]
I just tested FsPickler with Json.NET 7.0.1 and everything seems to be working fine. The latest FsPickler release relaxes the dependency constraint to incorporate 7.* releases.

**Comment by leo-gan** [comment]
Thanks!

Regards,

Leonid Ganeline
Microsoft Integration MVP (BizTalk Server)
http://geekswithblogs.net/leonidganeline/
