### ISSUE TITLE
Do not change binary format all the time

### ISSUE THREAD

**Issue by vasily-kirichenko** [nessos/FsPickler#57]
It's very painful, especially considering that other packages like Suave depend on FsPickler and updating them causes FsPickler update, which in turn causes huge problems on production, when we have serialized data which should be readable by next release of our system.

**Comment by eiriktsarpalis** [comment]
I'm sorry to hear that, but using FsPickler to persist data is a bad choice in the first place. It's been not been designed with version tolerance considerations in mind. If you need to keep using FsPickler for this type of usage, either commit to a specific version in production (perhaps forcing it on other libs by means of binding redirects) or use version tolerant, custom pickler declarations for the types that you are serializing.
