### ISSUE TITLE
FSharp.Core nuget 4.0.0.1

### ISSUE THREAD

**Issue by tebjan** [nessos/FsPickler#60]
hello, the latest FSharp.Core nuget is 4.0.0.1 is there a particular reason why you hardcoded the 3.1.2.5 version in the paket.dependencies file?

https://www.nuget.org/packages/FSharp.Core

**Comment by eiriktsarpalis** [comment]
No reason at all. I just pushed a nuget release that fixes this.

**Comment by eiriktsarpalis** [comment]
You might need to set a binding redirect in your application if you plan to use the latest version though.

**Comment by haf** [comment]
Please don't upgrade. https://github.com/SuaveIO/suave/commit/baf41867596adda3eee0eefa1552cca6f4f93ebd

**Comment by dsyme** [comment]
F# libraries should depend on the minimum version of FSharp.Core possible but allow later packages to be used by clients, to avoid forcing unnecessary dependencies on consumers (who can use binding redirects). So please use >= 3.1,2.5 as the dependency

**Comment by eiriktsarpalis** [comment]
For the record it was [this commit](85f668590d45f2f58bd07fc5cb22e570f2b462d1) that relaxes paket dependencies to support future FSharp.Core releases. Closing this as resolved.
