### ISSUE TITLE
What approach could be taken to improve the performance for a large object graph?

### ISSUE THREAD

**Issue by origfla** [nessos/FsPickler#65]
I have a relatively large object graph, potential for  ~ 500mb+ in size and the deserialization is dominating the performance of the application. 

FsPickler binary serialization is already performing admirably well compared to a few other alternatives (so well done for that) but I was wondering what avenues may be open to squeezing any more performance out of FsPickler?

**Comment by dsyme** [comment]
Profile the deserialization using some kind of .NET profiler?

**Comment by palladin** [comment]
@origfla If you want to contribute you can start by running PerfView on your scenario and try to identify potential performance hot spots.

**Comment by origfla** [comment]
Please see attached screenshot from my CPU profiling session in VS2015. All activity is spent inside FsPickler and I'm struggling to interpret things (as good or bad) once it's inside this library.

![capture](https://cloud.githubusercontent.com/assets/15446573/10991847/51ff8a72-8469-11e5-9dfa-777b9d4ef4a3.PNG)

**Comment by palladin** [comment]
Hmm interesting... I found this 
http://stackoverflow.com/questions/31433605/how-to-eliminate-time-spent-in-jit-tailcall-for-functions-that-are-genuinely-non
It seems that there is some performance correlation between struct, tails calls and 64 bit RyuJit.
I don't know if @dsyme knows something about this.

**Comment by eiriktsarpalis** [comment]
Serialization in general is a very intensive computation, particularly deserialization. FsPickler is a generic serialization library, so it always ensures that no cycles occur in an object graph which can be slow. If you have full control over the data types that you are serializing, I would recommend writing your own persist logic to squeeze out optimal serialization performance.

**Comment by origfla** [comment]
@eiriktsarpalis That seems to be where my journey has taken me to at the moment. In particular, using standard .NET `BinaryWriter` and `BinaryReader`. 

That said, in a simpler testing scenario, where there aren't the issues (1-3) as above, FsPickler is coming closer than I would have thought to the raw binary serialization and deserialization performance  - quite impressive given its generic nature.

**Comment by eiriktsarpalis** [comment]
Closing this then?
