### ISSUE TITLE
Diagnostics: When Pickler generation fails, it shows the wrong type in the Exception

### ISSUE THREAD

**Issue by 0x53A** [nessos/FsPickler#73]
I am currently trying to serialize a Roslyn compilation using FsPickler.
I have manually marked ``CSharpCompilation`` as Serializable using ``FsPickler.DeclareSerializable``.
Serialization still fails with the Exception that it can't serialize 'CSharpCompilation'
![image](https://cloud.githubusercontent.com/assets/4236651/15578369/7994e294-2360-11e6-91ba-eaf9b0d92f98.png)

Debugging shows the real non-serializable type, but this information was lost in the topmost exception:
![image](https://cloud.githubusercontent.com/assets/4236651/15578319/4cdc2622-2360-11e6-9c6c-d3cb927544c6.png)

Please pass the original exception through as an inner exception so it is possible to see for which type it failed without needing to attach a debugger.

**Comment by eiriktsarpalis** [comment]
Hi,

What is the precise exception that you are getting? I tried the following example:
```fsharp
[<AutoSerializable(false)>]
type Foo = { Foo : string }

type Bar = { Foo : Foo }

type Baz = { Bar : Bar }

FsPickler.GeneratePickler<Baz>()
```
which gives
```
Nessos.FsPickler.NonSerializableTypeException: Type 'FSI_0008+Baz' contains non-serializable field of type 'FSI_0008+Bar'.
```
This seems to contain sufficient debug information, since it points to the correct non-serializable field.

**Comment by 0x53A** [comment]
Hi, sorry for not providing a repro earlier.

This code
```
open Nessos.FsPickler

[<AutoSerializable(false)>]
type Foo = { Foo : string }

[<AutoSerializable(false)>]
type Bar = { Foo : Foo }

type Baz = { Bar : Bar }

[<EntryPoint>]
let main argv = 
    FsPickler.DeclareSerializable<Bar>()
    FsPickler.GeneratePickler<Baz>() |> ignore
    printfn "%A" argv
    0 // return an integer exit code

```
fails with
![image](https://cloud.githubusercontent.com/assets/4236651/15581157/811c738c-236b-11e6-8161-abf5f774b3ac.png)


If I add ``FsPickler.DeclareSerializable<Foo>()``, then it works.

Actual Result: The exception says Bar is not serializable
Expected Result: An inner exception which contains a mention of Foo.

**Comment by 0x53A** [comment]
Wow that was fast.
Thank you!

-		$exception	{"Type 'Program+Baz' contains non-serializable field of type 'Program+Bar'."}	

-		_innerException	{"Type 'Program+Bar' contains non-serializable field of type 'Program+Foo'."}

+		_innerException	{"Type 'Program+Foo' is not serializable."}
